# Generated by Django 5.0.1 on 2024-02-07 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Название')),
                ('slug', models.SlugField(blank=True, max_length=200, null=True, unique=True, verbose_name='URL')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание маршрута')),
                ('complexity', models.DecimalField(decimal_places=2, default=5.0, max_digits=3, verbose_name='Сложность')),
                ('duration', models.PositiveSmallIntegerField(verbose_name='Продолжительность')),
                ('distance', models.CharField(max_length=50, verbose_name='Протяженность')),
                ('image', models.ImageField(blank=True, null=True, upload_to='category_images', verbose_name='Изображение')),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=6, verbose_name='Цена маршрута')),
            ],
            options={
                'verbose_name': 'Маршрут',
                'verbose_name_plural': 'Маршруты',
                'db_table': 'route',
                'ordering': ('id',),
            },
        ),
    ]
